version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - asciicheck
    - bidichk
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - err113
    - errname
    - exptostd
    - gochecknoglobals
    - gocognit
    - gocritic
    - goconst
    - goheader
    - gosec
    - importas
    - makezero
    - mnd
    - nestif
    - nilnil
    - noctx
    - perfsprint
    - reassign
    - sloglint
    - tagalign
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wsl

formatters:
  enable:
    - goimports
    - gci
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  modules-download-mode: readonly