// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen --source=deps.go --destination=mocks/mock.go
//

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	reflect "reflect"

	models "github.com/hse-trpo-taxi/backend/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClientUseCase is a mock of ClientUseCase interface.
type MockClientUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockClientUseCaseMockRecorder
	isgomock struct{}
}

// MockClientUseCaseMockRecorder is the mock recorder for MockClientUseCase.
type MockClientUseCaseMockRecorder struct {
	mock *MockClientUseCase
}

// NewMockClientUseCase creates a new mock instance.
func NewMockClientUseCase(ctrl *gomock.Controller) *MockClientUseCase {
	mock := &MockClientUseCase{ctrl: ctrl}
	mock.recorder = &MockClientUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientUseCase) EXPECT() *MockClientUseCaseMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientUseCase) CreateClient(model *models.CreateClientModel) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", model)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientUseCaseMockRecorder) CreateClient(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientUseCase)(nil).CreateClient), model)
}

// DeleteClient mocks base method.
func (m *MockClientUseCase) DeleteClient(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockClientUseCaseMockRecorder) DeleteClient(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockClientUseCase)(nil).DeleteClient), id)
}

// GetClientById mocks base method.
func (m *MockClientUseCase) GetClientById(id uint32) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientById", id)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientById indicates an expected call of GetClientById.
func (mr *MockClientUseCaseMockRecorder) GetClientById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientById", reflect.TypeOf((*MockClientUseCase)(nil).GetClientById), id)
}

// GetClients mocks base method.
func (m *MockClientUseCase) GetClients() ([]*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients")
	ret0, _ := ret[0].([]*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClients indicates an expected call of GetClients.
func (mr *MockClientUseCaseMockRecorder) GetClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockClientUseCase)(nil).GetClients))
}

// UpdateClient mocks base method.
func (m *MockClientUseCase) UpdateClient(id uint32, model *models.UpdateClientModel) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", id, model)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientUseCaseMockRecorder) UpdateClient(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockClientUseCase)(nil).UpdateClient), id, model)
}

// MockClientRepository is a mock of ClientRepository interface.
type MockClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientRepositoryMockRecorder
	isgomock struct{}
}

// MockClientRepositoryMockRecorder is the mock recorder for MockClientRepository.
type MockClientRepositoryMockRecorder struct {
	mock *MockClientRepository
}

// NewMockClientRepository creates a new mock instance.
func NewMockClientRepository(ctrl *gomock.Controller) *MockClientRepository {
	mock := &MockClientRepository{ctrl: ctrl}
	mock.recorder = &MockClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRepository) EXPECT() *MockClientRepositoryMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientRepository) CreateClient(model *models.CreateClientModel) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", model)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientRepositoryMockRecorder) CreateClient(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientRepository)(nil).CreateClient), model)
}

// DeleteClient mocks base method.
func (m *MockClientRepository) DeleteClient(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockClientRepositoryMockRecorder) DeleteClient(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockClientRepository)(nil).DeleteClient), id)
}

// GetClientById mocks base method.
func (m *MockClientRepository) GetClientById(id uint32) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientById", id)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientById indicates an expected call of GetClientById.
func (mr *MockClientRepositoryMockRecorder) GetClientById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientById", reflect.TypeOf((*MockClientRepository)(nil).GetClientById), id)
}

// GetClients mocks base method.
func (m *MockClientRepository) GetClients() ([]*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients")
	ret0, _ := ret[0].([]*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClients indicates an expected call of GetClients.
func (mr *MockClientRepositoryMockRecorder) GetClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockClientRepository)(nil).GetClients))
}

// UpdateClient mocks base method.
func (m *MockClientRepository) UpdateClient(id uint32, model *models.UpdateClientModel) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", id, model)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientRepositoryMockRecorder) UpdateClient(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockClientRepository)(nil).UpdateClient), id, model)
}
