// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen --source=deps.go --destination=mocks/mock.go
//

// Package mock_drivers is a generated GoMock package.
package mock_drivers

import (
	reflect "reflect"

	models "github.com/hse-trpo-taxi/backend/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDriverUseCase is a mock of DriverUseCase interface.
type MockDriverUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDriverUseCaseMockRecorder
	isgomock struct{}
}

// MockDriverUseCaseMockRecorder is the mock recorder for MockDriverUseCase.
type MockDriverUseCaseMockRecorder struct {
	mock *MockDriverUseCase
}

// NewMockDriverUseCase creates a new mock instance.
func NewMockDriverUseCase(ctrl *gomock.Controller) *MockDriverUseCase {
	mock := &MockDriverUseCase{ctrl: ctrl}
	mock.recorder = &MockDriverUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverUseCase) EXPECT() *MockDriverUseCaseMockRecorder {
	return m.recorder
}

// CreateDriver mocks base method.
func (m *MockDriverUseCase) CreateDriver(model *models.CreateDriverModel) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDriver", model)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDriver indicates an expected call of CreateDriver.
func (mr *MockDriverUseCaseMockRecorder) CreateDriver(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDriver", reflect.TypeOf((*MockDriverUseCase)(nil).CreateDriver), model)
}

// DeleteDriver mocks base method.
func (m *MockDriverUseCase) DeleteDriver(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDriver", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDriver indicates an expected call of DeleteDriver.
func (mr *MockDriverUseCaseMockRecorder) DeleteDriver(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDriver", reflect.TypeOf((*MockDriverUseCase)(nil).DeleteDriver), id)
}

// GetDriverById mocks base method.
func (m *MockDriverUseCase) GetDriverById(id uint32) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverById", id)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverById indicates an expected call of GetDriverById.
func (mr *MockDriverUseCaseMockRecorder) GetDriverById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverById", reflect.TypeOf((*MockDriverUseCase)(nil).GetDriverById), id)
}

// GetDrivers mocks base method.
func (m *MockDriverUseCase) GetDrivers() ([]*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrivers")
	ret0, _ := ret[0].([]*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrivers indicates an expected call of GetDrivers.
func (mr *MockDriverUseCaseMockRecorder) GetDrivers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrivers", reflect.TypeOf((*MockDriverUseCase)(nil).GetDrivers))
}

// UpdateDriver mocks base method.
func (m *MockDriverUseCase) UpdateDriver(id uint32, model *models.UpdateDriverModel) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriver", id, model)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDriver indicates an expected call of UpdateDriver.
func (mr *MockDriverUseCaseMockRecorder) UpdateDriver(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriver", reflect.TypeOf((*MockDriverUseCase)(nil).UpdateDriver), id, model)
}

// MockDriverRepository is a mock of DriverRepository interface.
type MockDriverRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriverRepositoryMockRecorder
	isgomock struct{}
}

// MockDriverRepositoryMockRecorder is the mock recorder for MockDriverRepository.
type MockDriverRepositoryMockRecorder struct {
	mock *MockDriverRepository
}

// NewMockDriverRepository creates a new mock instance.
func NewMockDriverRepository(ctrl *gomock.Controller) *MockDriverRepository {
	mock := &MockDriverRepository{ctrl: ctrl}
	mock.recorder = &MockDriverRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverRepository) EXPECT() *MockDriverRepositoryMockRecorder {
	return m.recorder
}

// CreateDriver mocks base method.
func (m *MockDriverRepository) CreateDriver(model *models.CreateDriverModel) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDriver", model)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDriver indicates an expected call of CreateDriver.
func (mr *MockDriverRepositoryMockRecorder) CreateDriver(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDriver", reflect.TypeOf((*MockDriverRepository)(nil).CreateDriver), model)
}

// DeleteDriver mocks base method.
func (m *MockDriverRepository) DeleteDriver(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDriver", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDriver indicates an expected call of DeleteDriver.
func (mr *MockDriverRepositoryMockRecorder) DeleteDriver(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDriver", reflect.TypeOf((*MockDriverRepository)(nil).DeleteDriver), id)
}

// GetDriverById mocks base method.
func (m *MockDriverRepository) GetDriverById(id uint32) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverById", id)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverById indicates an expected call of GetDriverById.
func (mr *MockDriverRepositoryMockRecorder) GetDriverById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverById", reflect.TypeOf((*MockDriverRepository)(nil).GetDriverById), id)
}

// GetDrivers mocks base method.
func (m *MockDriverRepository) GetDrivers() ([]*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrivers")
	ret0, _ := ret[0].([]*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrivers indicates an expected call of GetDrivers.
func (mr *MockDriverRepositoryMockRecorder) GetDrivers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrivers", reflect.TypeOf((*MockDriverRepository)(nil).GetDrivers))
}

// UpdateDriver mocks base method.
func (m *MockDriverRepository) UpdateDriver(id uint32, model *models.UpdateDriverModel) (*models.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriver", id, model)
	ret0, _ := ret[0].(*models.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDriver indicates an expected call of UpdateDriver.
func (mr *MockDriverRepositoryMockRecorder) UpdateDriver(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriver", reflect.TypeOf((*MockDriverRepository)(nil).UpdateDriver), id, model)
}
