// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen --source=deps.go --destination=mocks/mock.go
//

// Package mock_cars is a generated GoMock package.
package mock_cars

import (
	reflect "reflect"

	models "github.com/hse-trpo-taxi/backend/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCarUseCase is a mock of CarUseCase interface.
type MockCarUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCarUseCaseMockRecorder
	isgomock struct{}
}

// MockCarUseCaseMockRecorder is the mock recorder for MockCarUseCase.
type MockCarUseCaseMockRecorder struct {
	mock *MockCarUseCase
}

// NewMockCarUseCase creates a new mock instance.
func NewMockCarUseCase(ctrl *gomock.Controller) *MockCarUseCase {
	mock := &MockCarUseCase{ctrl: ctrl}
	mock.recorder = &MockCarUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarUseCase) EXPECT() *MockCarUseCaseMockRecorder {
	return m.recorder
}

// CreateCar mocks base method.
func (m *MockCarUseCase) CreateCar(model *models.CreateCarModel) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", model)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockCarUseCaseMockRecorder) CreateCar(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockCarUseCase)(nil).CreateCar), model)
}

// DeleteCar mocks base method.
func (m *MockCarUseCase) DeleteCar(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCar", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCar indicates an expected call of DeleteCar.
func (mr *MockCarUseCaseMockRecorder) DeleteCar(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCar", reflect.TypeOf((*MockCarUseCase)(nil).DeleteCar), id)
}

// GetCarById mocks base method.
func (m *MockCarUseCase) GetCarById(id uint32) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarById", id)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarById indicates an expected call of GetCarById.
func (mr *MockCarUseCaseMockRecorder) GetCarById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarById", reflect.TypeOf((*MockCarUseCase)(nil).GetCarById), id)
}

// GetCars mocks base method.
func (m *MockCarUseCase) GetCars() ([]*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCars")
	ret0, _ := ret[0].([]*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCars indicates an expected call of GetCars.
func (mr *MockCarUseCaseMockRecorder) GetCars() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCars", reflect.TypeOf((*MockCarUseCase)(nil).GetCars))
}

// UpdateCar mocks base method.
func (m *MockCarUseCase) UpdateCar(id uint32, model *models.UpdateCarModel) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCar", id, model)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCar indicates an expected call of UpdateCar.
func (mr *MockCarUseCaseMockRecorder) UpdateCar(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCar", reflect.TypeOf((*MockCarUseCase)(nil).UpdateCar), id, model)
}

// MockCarRepository is a mock of CarRepository interface.
type MockCarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCarRepositoryMockRecorder
	isgomock struct{}
}

// MockCarRepositoryMockRecorder is the mock recorder for MockCarRepository.
type MockCarRepositoryMockRecorder struct {
	mock *MockCarRepository
}

// NewMockCarRepository creates a new mock instance.
func NewMockCarRepository(ctrl *gomock.Controller) *MockCarRepository {
	mock := &MockCarRepository{ctrl: ctrl}
	mock.recorder = &MockCarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarRepository) EXPECT() *MockCarRepositoryMockRecorder {
	return m.recorder
}

// CreateCar mocks base method.
func (m *MockCarRepository) CreateCar(model *models.CreateCarModel) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", model)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockCarRepositoryMockRecorder) CreateCar(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockCarRepository)(nil).CreateCar), model)
}

// DeleteCar mocks base method.
func (m *MockCarRepository) DeleteCar(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCar", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCar indicates an expected call of DeleteCar.
func (mr *MockCarRepositoryMockRecorder) DeleteCar(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCar", reflect.TypeOf((*MockCarRepository)(nil).DeleteCar), id)
}

// GetCarById mocks base method.
func (m *MockCarRepository) GetCarById(id uint32) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarById", id)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarById indicates an expected call of GetCarById.
func (mr *MockCarRepositoryMockRecorder) GetCarById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarById", reflect.TypeOf((*MockCarRepository)(nil).GetCarById), id)
}

// GetCars mocks base method.
func (m *MockCarRepository) GetCars() ([]*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCars")
	ret0, _ := ret[0].([]*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCars indicates an expected call of GetCars.
func (mr *MockCarRepositoryMockRecorder) GetCars() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCars", reflect.TypeOf((*MockCarRepository)(nil).GetCars))
}

// UpdateCar mocks base method.
func (m *MockCarRepository) UpdateCar(id uint32, model *models.UpdateCarModel) (*models.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCar", id, model)
	ret0, _ := ret[0].(*models.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCar indicates an expected call of UpdateCar.
func (mr *MockCarRepositoryMockRecorder) UpdateCar(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCar", reflect.TypeOf((*MockCarRepository)(nil).UpdateCar), id, model)
}
